<!-- BEGIN WEBSIDESTORY CODE v5 -->
<!-- COPYRIGHT 1998-2000 WEBSIDESTORY, INC. ALL RIGHTS RESERVED.  U.S. PATENT PENDING. -->
<!--	<script language="javascript"> var test=0;</script>
	<SCRIPT LANGUAGE="javascript1.1" src="http://ejs.hitbox.com/js?acct=DM5003297CVE&m=sportsya2&n=Club_Penarol"></SCRIPT>
	<SCRIPT LANGUAGE="javascript">
		if (test==0) {
			var dt, sv=10,ss="na",sc="na",ln="",pl="",rf,bn,ja,bv,x1,x2,x3,arg;
			rf=escape(document.referrer)+"";if((rf=="undefined")||(rf=="")){rf="bookmark";}
			bv=Math.round(parseFloat(navigator.appVersion)*100);bn=navigator.appName;
			if(bn!="Netscape"){dt=(newDate()).getHours();};if(bn.substring(0,9)=="Microsoft"){bn="MSIE";}
			if((bn=="MSIE")&&(parseInt(bv)==2)){bv=302;};ja="na";
			x2="<img src='http://ehg.hitbox.com/HG?hc=sportsya2&cd=1&hb=DM5003297CVE&n=Club_Penarol";
			x3="&cd=1&bt=2' border=0 height=1 width=1>";
			arg="&bn="+bn+"&bv="+bv+"&ss="+ss+"&sc="+sc+"&dt="+dt+"&sv="+sv;
			arg+="&ja="+ja+"&rf="+rf+"&ln="+ln+"&pl="+escape(pl);document.write(x2+arg+x3);
		}
	</SCRIPT>
	<script language="javascript1.2">document.write("<");document.write("!--");</script>
	<noscript><img src="http://ehg.hitbox.com/HG?hc=sportsya2&cd=1&hb=DM5003297CVE&n=Club_Penarol" border=0 height=1 width=1></noscript>
	<script language="javascript1.2">document.write("  --");document.write(">");</script>-->
<!-- END WEBSIDESTORY CODE  -->